# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Build and run tests"
  lane :test do
    scan(
      scheme: "VrInteractiveTracking",
      device: "iPhone 8",
      code_coverage: true,
      clean: true,
      output_directory: "/Users/distiller/project/fastlane/test_output"
    )
    slather(
      proj: "VrInteractiveTracking.xcodeproj",
      scheme: "VrInteractiveTracking",
      source_directory: "VrInteractiveTracking",
      output_directory: "/Users/distiller/project/fastlane/test_output/slather",
      html: true,
      ignore:['Tests/*']
    )
  end
end
